USE AdventureWorksDW2022
GO
SET STATISTICS TIME, IO ON

select [$Table].[ProductKey] as [ProductKey],
    [$Table].[ProductAlternateKey] as [ProductAlternateKey],
    [$Table].[ProductSubcategoryKey] as [ProductSubcategoryKey],
    [$Table].[WeightUnitMeasureCode] as [WeightUnitMeasureCode],
    [$Table].[SizeUnitMeasureCode] as [SizeUnitMeasureCode],
    [$Table].[EnglishProductName] as [EnglishProductName],
    [$Table].[SpanishProductName] as [SpanishProductName],
    [$Table].[FrenchProductName] as [FrenchProductName],
    [$Table].[StandardCost] as [StandardCost],
    [$Table].[FinishedGoodsFlag] as [FinishedGoodsFlag],
    [$Table].[Color] as [Color],
    [$Table].[SafetyStockLevel] as [SafetyStockLevel],
    [$Table].[ReorderPoint] as [ReorderPoint],
    [$Table].[ListPrice] as [ListPrice],
    [$Table].[Size] as [Size],
    [$Table].[SizeRange] as [SizeRange],
    [$Table].[Weight] as [Weight],
    [$Table].[DaysToManufacture] as [DaysToManufacture],
    [$Table].[ProductLine] as [ProductLine],
    [$Table].[DealerPrice] as [DealerPrice],
    [$Table].[Class] as [Class],
    [$Table].[Style] as [Style],
    [$Table].[ModelName] as [ModelName],
    [$Table].[LargePhoto] as [LargePhoto],
    [$Table].[EnglishDescription] as [EnglishDescription],
    [$Table].[FrenchDescription] as [FrenchDescription],
    [$Table].[ChineseDescription] as [ChineseDescription],
    [$Table].[ArabicDescription] as [ArabicDescription],
    [$Table].[HebrewDescription] as [HebrewDescription],
    [$Table].[ThaiDescription] as [ThaiDescription],
    [$Table].[GermanDescription] as [GermanDescription],
    [$Table].[JapaneseDescription] as [JapaneseDescription],
    [$Table].[TurkishDescription] as [TurkishDescription],
    [$Table].[StartDate] as [StartDate],
    [$Table].[EndDate] as [EndDate],
    [$Table].[Status] as [Status]
from [dbo].[DimProduct] as [$Table]